### PR TITLE
Use preg_match

### PR DESCRIPTION
**Pull request by 0xliam627**
Testing is in progress, please don't merge instead, give your opinion

### CODE REVIEW

**Comment by NhanAZ** [comment]
Original code:
```php
function containsProfanity(string $msg) {
	$profanities = [
		"fuck",
		"đụ"
	];
	foreach ($profanities as $profanitie) {
		if ((bool)strrchr(strtolower($msg), strval($profanitie))) {
			return true;
		}
	}
	return false;
}
var_dump(containsProfanity("đụ")); // bool(true)
```
Pulll requests code:
```php
function containsProfanity(string $msg) {
	$profanities = [
		"fuck",
		"đụ"
	];
	foreach ($profanities as $profanitie) {
		$pattern = '/\b' . $profanitie . '\b/i';
		if (preg_match($pattern, $msg) > 0) {
			return true;
		}
	}
	return false;
}
var_dump(containsProfanity("đụ")); // bool(false)
```

**Comment by 0xliam627** [comment]
```php
function containsProfanity(string $msg) {
	$profanities = [
		"fuck",
		"cặc"
	];
	$filterCount = sizeof($profanities);
	for($i=0; $i < $filterCount; $i++) {
		$value = preg_match('/\b'.$profanities[$i].'\b/i', $msg) > 0;
		if($value == true){
			return $value;
		}
	}
	return $value;
}
var_dump(containsProfanity("cặc")); // bool(true)
```
This code can be improved but there are still some words that still don't work

**Comment by NhanAZ** [comment]
Original code:
```php
function containsProfanity(string $msg) {
	$profanities = [
		"fuck",
		"đụ"
	];
	foreach ($profanities as $profanitie) {
		if ((bool)strrchr(strtolower($msg), strval($profanitie))) {
			return true;
		}
	}
	return false;
}
var_dump(containsProfanity("fuckfuck")); // bool(true)
```
Pulll requests code:
```php
<?
function containsProfanity(string $msg) {
	$profanities = [
		"fuck",
		"đụ"
	];
	$filterCount = sizeof($profanities);
	for($i=0; $i < $filterCount; $i++) {
		$value = preg_match('/\b'.$profanities[$i].'\b/i', $msg) > 0;
		if($value == true){
			return $value;
		}
	}
	return $value;
}
var_dump(containsProfanity("fuckfuck")); // bool(false)
```

**Comment by 0xliam627** [comment]
```php
function containsProfanity(string $msg) {
	$profanities = [
		"fuck",
		"đụ"
	];
	$filterCount = sizeof($profanities);
	for($i=0; $i < $filterCount; $i++) {
		$value = preg_match('/'.$profanities[$i].'/iu', $msg) > 0;
		if($value == true){
			return $value;
		}
	}
	return $value;
}
var_dump(containsProfanity("fuckfuck")); // bool(true)
```

**Review by NhanAZ — APPROVED** [review]
Thank you for your contribution. I hope I get your PR in the future!

**Pull request merged**
